# Generated by Django 2.0.7 on 2018-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
