# Generated by Django 2.0.7 on 2018-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_user_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user1.jpg', upload_to='photos'),
        ),
    ]
